"""empty message

Revision ID: ee97b061192c
Revises: 98f46c5363ce
Create Date: 2020-11-22 14:15:57.500231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee97b061192c'
down_revision = '98f46c5363ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.drop_constraint('shows_Venue_id_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'Venue', ['venue_id'], ['id'])
    op.drop_column('shows', 'Venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('Venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_Venue_id_fkey', 'shows', 'Venue', ['Venue_id'], ['id'])
    op.drop_column('shows', 'venue_id')
    # ### end Alembic commands ###
